### ISSUE TITLE
Update reference optimizer to have 2-stage model

### ISSUE THREAD

**Issue by Groostav** [EmpowerOperations/volition#10]
> As a volition API developer I want the reference optimizer to behave like OASIS in its handling of API calls around model changes, such when I `register`, `updateNode`, and `changeName`,  

OASIS is moving toward having a two stage model, where API calls change a staging area that users have to explicitly hook up (through UI elements or OPYL files). The reference optimizer needs to be updated to include this feature, so that users who are playing with the reference optimizer will understand the interventions that will be needed in OASIS.

**Comment by VinnieH** [comment]
Currently, the reference proxy is missing the layer of proxy setup, which is the functional setup represented as the setup layer. 

This will help us:
 1. Enable wider plugin setup, e.g. a plugin node passing no ranges of its inputs, like the current version of ansys plugin
 2. Explore sync up problem happening. 
  - Implementing problem finding service
  - minimizing mismatch between run setup and simulation 
  - adding problem notification
  - explore the UI to display above information information
 3. Explore how setup are created, our goal here is maximize flexibility and recoverability and minimize confusion and memorization for user to setup a connection. This include how we present register simulation and its connection state and further explore how we deal with unreachable connection. 

The goal for this is implementing the base ground of the setup stage and exploring the above 3 as much as possible including updating reference. This should minimize but shouldn't limited by changes on API and reference plugin.

**Comment by VinnieH** [comment]
1 hour
> update the issue and bring in some idea form the issues in setup 

1 hour

**Comment by VinnieH** [comment]
`7` hours 
> tornadofx
> update the registration stage 

`8` hours

**Comment by VinnieH** [comment]
7 hours
- most of stuff going 
- exploring on error state 

15 hours

**Comment by VinnieH** [comment]
`3` hours 
> working on unregister 

totally `18` hours

**Comment by VinnieH** [comment]
7 hours
> closing up thing 

totally `25` hours

**Comment by VinnieH** [comment]
`6` hours
> working on edit in table 

totally `31` hours

**Comment by VinnieH** [comment]
`5` hours
>finishing up the issue
>new invalidation system

totally `36` hours

**Comment by VinnieH** [comment]
3 hours
> finishing up, create a PR 

totally 41 hours

**Comment by VinnieH** [comment]
`5` hours
>PR stuff, refactoring

totally 46 hours

**Comment by VinnieH** [comment]
6 hours
> PR stuff, refactoring, ready to read

totally 51 hours

**Comment by VinnieH** [comment]
`6` hours
> PR and exploration 

totally `57` hours
