### ISSUE TITLE
add headless mode for reference optimizer 

### ISSUE THREAD

**Issue by VinnieH** [EmpowerOperations/volition#12]
> As API user, reference optimizer should be able to run in headless mode so I can experiment cloud implementation 

This issue is aiming to do the following
- figuring out UI dependency and make add headless mode
- Adding extra api call if needed to support running oasis headlessly, e.g. add auto configure
- better status update with returning message, e.g. issues when call start etc

The goal here is making reference full controllable with only plugin

stretch goal:
- run this thing headlessly on a remote PC, pass connection string by env param or whatever

**Comment by Groostav** [comment]
some notes:
- not including anything for continue
- will include the optimization mat (result sheet) on the completion message from the ref optimizer
- will include opt metadata (bounds) and convergence criteria (eval count, etc) on the start optimization message

**Comment by Groostav** [comment]
some input criteria:
- do you have input variables?
- do all input variables have bounds?
- do you have output variables?

one more point:
- auto import should be exclusive: when you start an optimization for the plugin X _only plugin X should be involved in the optimization_

**Comment by VinnieH** [comment]
`10` hours
> start on the issue and get mot function going 

`10` in total

**Comment by VinnieH** [comment]
Moved over due to emergency issue take up time from iteration 149

**Comment by VinnieH** [comment]
`5` hours
>working with log/console display

totally 15 hours

**Comment by VinnieH** [comment]
`6` hours
> working on the todo list

totally `21` horus

**Comment by VinnieH** [comment]
5 hours
> more todo list, close to finish 

 totally `26` hours

**Comment by VinnieH** [comment]
1 hours
> message and boolean stuff

totally `31` hours

**Comment by VinnieH** [comment]
7 hours
> refactoring work

totally 38 hours

**Comment by VinnieH** [comment]
5 hours
>event bus, functional testing 

totally 43 hours

**Comment by VinnieH** [comment]
7 hours
> demo, bug fix, cmd

totally 50 hours

**Comment by VinnieH** [comment]
`6` hours
> logging, clean up

totally `56` hours

**Comment by VinnieH** [comment]
`7` hours
>working on PR

totally `63` hours

**Comment by VinnieH** [comment]
`10` hours
> thinking about following up
> PR 
> rebase 

totally `10` hours

**Comment by VinnieH** [comment]
`3` hours
> RP

totally `76` hours
