### ISSUE TITLE
Fix CI problem

### ISSUE THREAD

**Issue by VinnieH** [EmpowerOperations/volition#13]
Current agent `Larvitar` having problem running due to some javadoc problem when running gradle target `:api:javadoc`
with error message `Unable to find the 'javadoc' executable. Tried the java home: C:\BuildAgent\jre and the PATH. We will assume the executable can be ran in the current working folder.`

This issue is invitage the problem and fix it.

For now, the build agent is exclude running volition repo.

**Comment by Groostav** [comment]
larvatar DNE, and there are no current issues on teamcity
