### ISSUE TITLE
Prep documentation, onboarding

### ISSUE THREAD

**Issue by Groostav** [EmpowerOperations/volition#2]
> As the CTO I want this documentation to have some on boarding documentation for new users so that I can send invites to this repository and know that recipients might reasonably know how to move forward.

This issue is to add some minimal documentation on getting started!

**Comment by Groostav** [comment]
Cenk spent `2` hours on this

total: `2` hours

**Comment by VinnieH** [comment]
Geoff spent `6` hours
> get the repo ready

totally `8` hours

**Comment by NavalOrange** [comment]
`3` hours from geoff

>whiteboarding
sending emails

up to `11`
