### ISSUE TITLE
Reference optimizer and client update

### ISSUE THREAD

**Issue by VinnieH** [EmpowerOperations/volition#8]
Here is the a list of issues we want to do:
- General reference optimizer improvement, per tool action and management
- better connection control
- remove some confusing testing functionalities
- Bound setup for ref optimizer
- Cancellation flow/maybe a time out feature
- deterministic input 

Our goal here:
1. mimic as close as possible to relevant OASIS behaviors, as we are now have better understanding what oasis is doing with the plugin. Mainly around cancellation, time out, etc
2. providing functionality that help functional user testing their implementation, with best practice.

**Comment by VinnieH** [comment]
`15` hours total
> update on the UI, making fxml and working with controllers

totally `15` hours

**Comment by VinnieH** [comment]
8 hours 
> finishing up the new UI
> add time out
> some basic status message

totally `23` hours

**Comment by VinnieH** [comment]
`5` hours 
> finishing up and create a PR 

totally `28` hours

**Comment by VinnieH** [comment]
`6` hours
> PR stuff and some update for the talk

totally `34` hours

**Comment by VinnieH** [comment]
5 hours 
> PR, refactoring 

totally `39` hours

**Comment by VinnieH** [comment]
5 hours 
> looking into channel stuff

totally 44 hours

**Comment by Groostav** [comment]
I spent `2` hours here

> reading PR
> looking into problems with bundled executable
> syncing up on problems with the `error` flow

**Comment by VinnieH** [comment]
2 hours
- fix the problem with the build with resource

totally 46 + 2 missing from Geoff's comment `48` hours

**Comment by VinnieH** [comment]
`6` hours 
- PR 

`54` hours

**Comment by VinnieH** [comment]
`3` horus 
- PR 

totally `57` horus
